
NAME = 'Scale Obs 200'

AGENTS = ['A', 'B', 'C', 'D']

OBSERVATIONS = [{'author': 'A',
  'before': [],
  'message': 'Redecentralization of the Web',
  'observation_id': 0,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [0],
  'message': 'Redecentralization of the Web',
  'observation_id': 1,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [1],
  'message': 'Redecentralization of the Web',
  'observation_id': 2,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [2],
  'message': 'Redecentralization of the Web',
  'observation_id': 3,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [3],
  'message': 'Redecentralization of the Web',
  'observation_id': 4,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [4],
  'message': 'Redecentralization of the Web',
  'observation_id': 5,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [5],
  'message': 'Redecentralization of the Web',
  'observation_id': 6,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [6],
  'message': 'Redecentralization of the Web',
  'observation_id': 7,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [7],
  'message': 'Redecentralization of the Web',
  'observation_id': 8,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [8],
  'message': 'Redecentralization of the Web',
  'observation_id': 9,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [9],
  'message': 'Redecentralization of the Web',
  'observation_id': 10,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [10],
  'message': 'Redecentralization of the Web',
  'observation_id': 11,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [11],
  'message': 'Redecentralization of the Web',
  'observation_id': 12,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [12],
  'message': 'Redecentralization of the Web',
  'observation_id': 13,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [13],
  'message': 'Redecentralization of the Web',
  'observation_id': 14,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [14],
  'message': 'Redecentralization of the Web',
  'observation_id': 15,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [15],
  'message': 'Redecentralization of the Web',
  'observation_id': 16,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [16],
  'message': 'Redecentralization of the Web',
  'observation_id': 17,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [17],
  'message': 'Redecentralization of the Web',
  'observation_id': 18,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [18],
  'message': 'Redecentralization of the Web',
  'observation_id': 19,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [19],
  'message': 'Redecentralization of the Web',
  'observation_id': 20,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [20],
  'message': 'Redecentralization of the Web',
  'observation_id': 21,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [21],
  'message': 'Redecentralization of the Web',
  'observation_id': 22,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [22],
  'message': 'Redecentralization of the Web',
  'observation_id': 23,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [23],
  'message': 'Redecentralization of the Web',
  'observation_id': 24,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [24],
  'message': 'Redecentralization of the Web',
  'observation_id': 25,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [25],
  'message': 'Redecentralization of the Web',
  'observation_id': 26,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [26],
  'message': 'Redecentralization of the Web',
  'observation_id': 27,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [27],
  'message': 'Redecentralization of the Web',
  'observation_id': 28,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [28],
  'message': 'Redecentralization of the Web',
  'observation_id': 29,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [29],
  'message': 'Redecentralization of the Web',
  'observation_id': 30,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [30],
  'message': 'Redecentralization of the Web',
  'observation_id': 31,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [31],
  'message': 'Redecentralization of the Web',
  'observation_id': 32,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [32],
  'message': 'Redecentralization of the Web',
  'observation_id': 33,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [33],
  'message': 'Redecentralization of the Web',
  'observation_id': 34,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [34],
  'message': 'Redecentralization of the Web',
  'observation_id': 35,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [35],
  'message': 'Redecentralization of the Web',
  'observation_id': 36,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [36],
  'message': 'Redecentralization of the Web',
  'observation_id': 37,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [37],
  'message': 'Redecentralization of the Web',
  'observation_id': 38,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [38],
  'message': 'Redecentralization of the Web',
  'observation_id': 39,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [39],
  'message': 'Redecentralization of the Web',
  'observation_id': 40,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [40],
  'message': 'Redecentralization of the Web',
  'observation_id': 41,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [41],
  'message': 'Redecentralization of the Web',
  'observation_id': 42,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [42],
  'message': 'Redecentralization of the Web',
  'observation_id': 43,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [43],
  'message': 'Redecentralization of the Web',
  'observation_id': 44,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [44],
  'message': 'Redecentralization of the Web',
  'observation_id': 45,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [45],
  'message': 'Redecentralization of the Web',
  'observation_id': 46,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [46],
  'message': 'Redecentralization of the Web',
  'observation_id': 47,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [47],
  'message': 'Redecentralization of the Web',
  'observation_id': 48,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [48],
  'message': 'Redecentralization of the Web',
  'observation_id': 49,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [49],
  'message': 'Redecentralization of the Web',
  'observation_id': 50,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [50],
  'message': 'Redecentralization of the Web',
  'observation_id': 51,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [51],
  'message': 'Redecentralization of the Web',
  'observation_id': 52,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [52],
  'message': 'Redecentralization of the Web',
  'observation_id': 53,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [53],
  'message': 'Redecentralization of the Web',
  'observation_id': 54,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [54],
  'message': 'Redecentralization of the Web',
  'observation_id': 55,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [55],
  'message': 'Redecentralization of the Web',
  'observation_id': 56,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [56],
  'message': 'Redecentralization of the Web',
  'observation_id': 57,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [57],
  'message': 'Redecentralization of the Web',
  'observation_id': 58,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [58],
  'message': 'Redecentralization of the Web',
  'observation_id': 59,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [59],
  'message': 'Redecentralization of the Web',
  'observation_id': 60,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [60],
  'message': 'Redecentralization of the Web',
  'observation_id': 61,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [61],
  'message': 'Redecentralization of the Web',
  'observation_id': 62,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [62],
  'message': 'Redecentralization of the Web',
  'observation_id': 63,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [63],
  'message': 'Redecentralization of the Web',
  'observation_id': 64,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [64],
  'message': 'Redecentralization of the Web',
  'observation_id': 65,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [65],
  'message': 'Redecentralization of the Web',
  'observation_id': 66,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [66],
  'message': 'Redecentralization of the Web',
  'observation_id': 67,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [67],
  'message': 'Redecentralization of the Web',
  'observation_id': 68,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [68],
  'message': 'Redecentralization of the Web',
  'observation_id': 69,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [69],
  'message': 'Redecentralization of the Web',
  'observation_id': 70,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [70],
  'message': 'Redecentralization of the Web',
  'observation_id': 71,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [71],
  'message': 'Redecentralization of the Web',
  'observation_id': 72,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [72],
  'message': 'Redecentralization of the Web',
  'observation_id': 73,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [73],
  'message': 'Redecentralization of the Web',
  'observation_id': 74,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [74],
  'message': 'Redecentralization of the Web',
  'observation_id': 75,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [75],
  'message': 'Redecentralization of the Web',
  'observation_id': 76,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [76],
  'message': 'Redecentralization of the Web',
  'observation_id': 77,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [77],
  'message': 'Redecentralization of the Web',
  'observation_id': 78,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [78],
  'message': 'Redecentralization of the Web',
  'observation_id': 79,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [79],
  'message': 'Redecentralization of the Web',
  'observation_id': 80,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [80],
  'message': 'Redecentralization of the Web',
  'observation_id': 81,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [81],
  'message': 'Redecentralization of the Web',
  'observation_id': 82,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [82],
  'message': 'Redecentralization of the Web',
  'observation_id': 83,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [83],
  'message': 'Redecentralization of the Web',
  'observation_id': 84,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [84],
  'message': 'Redecentralization of the Web',
  'observation_id': 85,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [85],
  'message': 'Redecentralization of the Web',
  'observation_id': 86,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [86],
  'message': 'Redecentralization of the Web',
  'observation_id': 87,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [87],
  'message': 'Redecentralization of the Web',
  'observation_id': 88,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [88],
  'message': 'Redecentralization of the Web',
  'observation_id': 89,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [89],
  'message': 'Redecentralization of the Web',
  'observation_id': 90,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [90],
  'message': 'Redecentralization of the Web',
  'observation_id': 91,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [91],
  'message': 'Redecentralization of the Web',
  'observation_id': 92,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [92],
  'message': 'Redecentralization of the Web',
  'observation_id': 93,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [93],
  'message': 'Redecentralization of the Web',
  'observation_id': 94,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [94],
  'message': 'Redecentralization of the Web',
  'observation_id': 95,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [95],
  'message': 'Redecentralization of the Web',
  'observation_id': 96,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [96],
  'message': 'Redecentralization of the Web',
  'observation_id': 97,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [97],
  'message': 'Redecentralization of the Web',
  'observation_id': 98,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [98],
  'message': 'Redecentralization of the Web',
  'observation_id': 99,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [99],
  'message': 'Redecentralization of the Web',
  'observation_id': 100,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [100],
  'message': 'Redecentralization of the Web',
  'observation_id': 101,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [101],
  'message': 'Redecentralization of the Web',
  'observation_id': 102,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [102],
  'message': 'Redecentralization of the Web',
  'observation_id': 103,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [103],
  'message': 'Redecentralization of the Web',
  'observation_id': 104,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [104],
  'message': 'Redecentralization of the Web',
  'observation_id': 105,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [105],
  'message': 'Redecentralization of the Web',
  'observation_id': 106,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [106],
  'message': 'Redecentralization of the Web',
  'observation_id': 107,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [107],
  'message': 'Redecentralization of the Web',
  'observation_id': 108,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [108],
  'message': 'Redecentralization of the Web',
  'observation_id': 109,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [109],
  'message': 'Redecentralization of the Web',
  'observation_id': 110,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [110],
  'message': 'Redecentralization of the Web',
  'observation_id': 111,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [111],
  'message': 'Redecentralization of the Web',
  'observation_id': 112,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [112],
  'message': 'Redecentralization of the Web',
  'observation_id': 113,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [113],
  'message': 'Redecentralization of the Web',
  'observation_id': 114,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [114],
  'message': 'Redecentralization of the Web',
  'observation_id': 115,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [115],
  'message': 'Redecentralization of the Web',
  'observation_id': 116,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [116],
  'message': 'Redecentralization of the Web',
  'observation_id': 117,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [117],
  'message': 'Redecentralization of the Web',
  'observation_id': 118,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [118],
  'message': 'Redecentralization of the Web',
  'observation_id': 119,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [119],
  'message': 'Redecentralization of the Web',
  'observation_id': 120,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [120],
  'message': 'Redecentralization of the Web',
  'observation_id': 121,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [121],
  'message': 'Redecentralization of the Web',
  'observation_id': 122,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [122],
  'message': 'Redecentralization of the Web',
  'observation_id': 123,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [123],
  'message': 'Redecentralization of the Web',
  'observation_id': 124,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [124],
  'message': 'Redecentralization of the Web',
  'observation_id': 125,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [125],
  'message': 'Redecentralization of the Web',
  'observation_id': 126,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [126],
  'message': 'Redecentralization of the Web',
  'observation_id': 127,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [127],
  'message': 'Redecentralization of the Web',
  'observation_id': 128,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [128],
  'message': 'Redecentralization of the Web',
  'observation_id': 129,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [129],
  'message': 'Redecentralization of the Web',
  'observation_id': 130,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [130],
  'message': 'Redecentralization of the Web',
  'observation_id': 131,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [131],
  'message': 'Redecentralization of the Web',
  'observation_id': 132,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [132],
  'message': 'Redecentralization of the Web',
  'observation_id': 133,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [133],
  'message': 'Redecentralization of the Web',
  'observation_id': 134,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [134],
  'message': 'Redecentralization of the Web',
  'observation_id': 135,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [135],
  'message': 'Redecentralization of the Web',
  'observation_id': 136,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [136],
  'message': 'Redecentralization of the Web',
  'observation_id': 137,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [137],
  'message': 'Redecentralization of the Web',
  'observation_id': 138,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [138],
  'message': 'Redecentralization of the Web',
  'observation_id': 139,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [139],
  'message': 'Redecentralization of the Web',
  'observation_id': 140,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [140],
  'message': 'Redecentralization of the Web',
  'observation_id': 141,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [141],
  'message': 'Redecentralization of the Web',
  'observation_id': 142,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [142],
  'message': 'Redecentralization of the Web',
  'observation_id': 143,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [143],
  'message': 'Redecentralization of the Web',
  'observation_id': 144,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [144],
  'message': 'Redecentralization of the Web',
  'observation_id': 145,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [145],
  'message': 'Redecentralization of the Web',
  'observation_id': 146,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [146],
  'message': 'Redecentralization of the Web',
  'observation_id': 147,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [147],
  'message': 'Redecentralization of the Web',
  'observation_id': 148,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [148],
  'message': 'Redecentralization of the Web',
  'observation_id': 149,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [149],
  'message': 'Redecentralization of the Web',
  'observation_id': 150,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [150],
  'message': 'Redecentralization of the Web',
  'observation_id': 151,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [151],
  'message': 'Redecentralization of the Web',
  'observation_id': 152,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [152],
  'message': 'Redecentralization of the Web',
  'observation_id': 153,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [153],
  'message': 'Redecentralization of the Web',
  'observation_id': 154,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [154],
  'message': 'Redecentralization of the Web',
  'observation_id': 155,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [155],
  'message': 'Redecentralization of the Web',
  'observation_id': 156,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [156],
  'message': 'Redecentralization of the Web',
  'observation_id': 157,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [157],
  'message': 'Redecentralization of the Web',
  'observation_id': 158,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [158],
  'message': 'Redecentralization of the Web',
  'observation_id': 159,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [159],
  'message': 'Redecentralization of the Web',
  'observation_id': 160,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [160],
  'message': 'Redecentralization of the Web',
  'observation_id': 161,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [161],
  'message': 'Redecentralization of the Web',
  'observation_id': 162,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [162],
  'message': 'Redecentralization of the Web',
  'observation_id': 163,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [163],
  'message': 'Redecentralization of the Web',
  'observation_id': 164,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [164],
  'message': 'Redecentralization of the Web',
  'observation_id': 165,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [165],
  'message': 'Redecentralization of the Web',
  'observation_id': 166,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [166],
  'message': 'Redecentralization of the Web',
  'observation_id': 167,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [167],
  'message': 'Redecentralization of the Web',
  'observation_id': 168,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [168],
  'message': 'Redecentralization of the Web',
  'observation_id': 169,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [169],
  'message': 'Redecentralization of the Web',
  'observation_id': 170,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [170],
  'message': 'Redecentralization of the Web',
  'observation_id': 171,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [171],
  'message': 'Redecentralization of the Web',
  'observation_id': 172,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [172],
  'message': 'Redecentralization of the Web',
  'observation_id': 173,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [173],
  'message': 'Redecentralization of the Web',
  'observation_id': 174,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [174],
  'message': 'Redecentralization of the Web',
  'observation_id': 175,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [175],
  'message': 'Redecentralization of the Web',
  'observation_id': 176,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [176],
  'message': 'Redecentralization of the Web',
  'observation_id': 177,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [177],
  'message': 'Redecentralization of the Web',
  'observation_id': 178,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [178],
  'message': 'Redecentralization of the Web',
  'observation_id': 179,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [179],
  'message': 'Redecentralization of the Web',
  'observation_id': 180,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [180],
  'message': 'Redecentralization of the Web',
  'observation_id': 181,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [181],
  'message': 'Redecentralization of the Web',
  'observation_id': 182,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [182],
  'message': 'Redecentralization of the Web',
  'observation_id': 183,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [183],
  'message': 'Redecentralization of the Web',
  'observation_id': 184,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [184],
  'message': 'Redecentralization of the Web',
  'observation_id': 185,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [185],
  'message': 'Redecentralization of the Web',
  'observation_id': 186,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [186],
  'message': 'Redecentralization of the Web',
  'observation_id': 187,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [187],
  'message': 'Redecentralization of the Web',
  'observation_id': 188,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [188],
  'message': 'Redecentralization of the Web',
  'observation_id': 189,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [189],
  'message': 'Redecentralization of the Web',
  'observation_id': 190,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [190],
  'message': 'Redecentralization of the Web',
  'observation_id': 191,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [191],
  'message': 'Redecentralization of the Web',
  'observation_id': 192,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [192],
  'message': 'Redecentralization of the Web',
  'observation_id': 193,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [193],
  'message': 'Redecentralization of the Web',
  'observation_id': 194,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [194],
  'message': 'Redecentralization of the Web',
  'observation_id': 195,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [195],
  'message': 'Redecentralization of the Web',
  'observation_id': 196,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [196],
  'message': 'Redecentralization of the Web',
  'observation_id': 197,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [197],
  'message': 'Redecentralization of the Web',
  'observation_id': 198,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [198],
  'message': 'Redecentralization of the Web',
  'observation_id': 199,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'}]

HISTORY = {'A': {'B': 1.0, 'C': 1.0, 'D': 1.0},
 'B': {'A': 0, 'C': 0, 'D': 1.0},
 'C': {'A': 1.0, 'B': 1.0, 'D': 1.0},
 'D': {'A': 1.0, 'B': 1.0, 'C': 1.0}}

SCALES_PER_AGENT = {'A': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'B': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'C': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'D': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'}}

METRICS_PER_AGENT = {'A': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'B': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'C': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'D': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}}}

DESCRIPTION = 'Scalability Test with observation upscaling for WI 2020'

