
NAME = 'Scale Obs 100'

AGENTS = ['A', 'B', 'C', 'D']

OBSERVATIONS = [{'author': 'A',
  'before': [],
  'message': 'Redecentralization of the Web',
  'observation_id': 0,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [0],
  'message': 'Redecentralization of the Web',
  'observation_id': 1,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [1],
  'message': 'Redecentralization of the Web',
  'observation_id': 2,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [2],
  'message': 'Redecentralization of the Web',
  'observation_id': 3,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [3],
  'message': 'Redecentralization of the Web',
  'observation_id': 4,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [4],
  'message': 'Redecentralization of the Web',
  'observation_id': 5,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [5],
  'message': 'Redecentralization of the Web',
  'observation_id': 6,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [6],
  'message': 'Redecentralization of the Web',
  'observation_id': 7,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [7],
  'message': 'Redecentralization of the Web',
  'observation_id': 8,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [8],
  'message': 'Redecentralization of the Web',
  'observation_id': 9,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [9],
  'message': 'Redecentralization of the Web',
  'observation_id': 10,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [10],
  'message': 'Redecentralization of the Web',
  'observation_id': 11,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [11],
  'message': 'Redecentralization of the Web',
  'observation_id': 12,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [12],
  'message': 'Redecentralization of the Web',
  'observation_id': 13,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [13],
  'message': 'Redecentralization of the Web',
  'observation_id': 14,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [14],
  'message': 'Redecentralization of the Web',
  'observation_id': 15,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [15],
  'message': 'Redecentralization of the Web',
  'observation_id': 16,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [16],
  'message': 'Redecentralization of the Web',
  'observation_id': 17,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [17],
  'message': 'Redecentralization of the Web',
  'observation_id': 18,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [18],
  'message': 'Redecentralization of the Web',
  'observation_id': 19,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [19],
  'message': 'Redecentralization of the Web',
  'observation_id': 20,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [20],
  'message': 'Redecentralization of the Web',
  'observation_id': 21,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [21],
  'message': 'Redecentralization of the Web',
  'observation_id': 22,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [22],
  'message': 'Redecentralization of the Web',
  'observation_id': 23,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [23],
  'message': 'Redecentralization of the Web',
  'observation_id': 24,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [24],
  'message': 'Redecentralization of the Web',
  'observation_id': 25,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [25],
  'message': 'Redecentralization of the Web',
  'observation_id': 26,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [26],
  'message': 'Redecentralization of the Web',
  'observation_id': 27,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [27],
  'message': 'Redecentralization of the Web',
  'observation_id': 28,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [28],
  'message': 'Redecentralization of the Web',
  'observation_id': 29,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [29],
  'message': 'Redecentralization of the Web',
  'observation_id': 30,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [30],
  'message': 'Redecentralization of the Web',
  'observation_id': 31,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [31],
  'message': 'Redecentralization of the Web',
  'observation_id': 32,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [32],
  'message': 'Redecentralization of the Web',
  'observation_id': 33,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [33],
  'message': 'Redecentralization of the Web',
  'observation_id': 34,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [34],
  'message': 'Redecentralization of the Web',
  'observation_id': 35,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [35],
  'message': 'Redecentralization of the Web',
  'observation_id': 36,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [36],
  'message': 'Redecentralization of the Web',
  'observation_id': 37,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [37],
  'message': 'Redecentralization of the Web',
  'observation_id': 38,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [38],
  'message': 'Redecentralization of the Web',
  'observation_id': 39,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [39],
  'message': 'Redecentralization of the Web',
  'observation_id': 40,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [40],
  'message': 'Redecentralization of the Web',
  'observation_id': 41,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [41],
  'message': 'Redecentralization of the Web',
  'observation_id': 42,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [42],
  'message': 'Redecentralization of the Web',
  'observation_id': 43,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [43],
  'message': 'Redecentralization of the Web',
  'observation_id': 44,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [44],
  'message': 'Redecentralization of the Web',
  'observation_id': 45,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [45],
  'message': 'Redecentralization of the Web',
  'observation_id': 46,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [46],
  'message': 'Redecentralization of the Web',
  'observation_id': 47,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [47],
  'message': 'Redecentralization of the Web',
  'observation_id': 48,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [48],
  'message': 'Redecentralization of the Web',
  'observation_id': 49,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [49],
  'message': 'Redecentralization of the Web',
  'observation_id': 50,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [50],
  'message': 'Redecentralization of the Web',
  'observation_id': 51,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [51],
  'message': 'Redecentralization of the Web',
  'observation_id': 52,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [52],
  'message': 'Redecentralization of the Web',
  'observation_id': 53,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [53],
  'message': 'Redecentralization of the Web',
  'observation_id': 54,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [54],
  'message': 'Redecentralization of the Web',
  'observation_id': 55,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [55],
  'message': 'Redecentralization of the Web',
  'observation_id': 56,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [56],
  'message': 'Redecentralization of the Web',
  'observation_id': 57,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [57],
  'message': 'Redecentralization of the Web',
  'observation_id': 58,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [58],
  'message': 'Redecentralization of the Web',
  'observation_id': 59,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [59],
  'message': 'Redecentralization of the Web',
  'observation_id': 60,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [60],
  'message': 'Redecentralization of the Web',
  'observation_id': 61,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [61],
  'message': 'Redecentralization of the Web',
  'observation_id': 62,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [62],
  'message': 'Redecentralization of the Web',
  'observation_id': 63,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [63],
  'message': 'Redecentralization of the Web',
  'observation_id': 64,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [64],
  'message': 'Redecentralization of the Web',
  'observation_id': 65,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [65],
  'message': 'Redecentralization of the Web',
  'observation_id': 66,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [66],
  'message': 'Redecentralization of the Web',
  'observation_id': 67,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [67],
  'message': 'Redecentralization of the Web',
  'observation_id': 68,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [68],
  'message': 'Redecentralization of the Web',
  'observation_id': 69,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [69],
  'message': 'Redecentralization of the Web',
  'observation_id': 70,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [70],
  'message': 'Redecentralization of the Web',
  'observation_id': 71,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [71],
  'message': 'Redecentralization of the Web',
  'observation_id': 72,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [72],
  'message': 'Redecentralization of the Web',
  'observation_id': 73,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [73],
  'message': 'Redecentralization of the Web',
  'observation_id': 74,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [74],
  'message': 'Redecentralization of the Web',
  'observation_id': 75,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [75],
  'message': 'Redecentralization of the Web',
  'observation_id': 76,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [76],
  'message': 'Redecentralization of the Web',
  'observation_id': 77,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [77],
  'message': 'Redecentralization of the Web',
  'observation_id': 78,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [78],
  'message': 'Redecentralization of the Web',
  'observation_id': 79,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [79],
  'message': 'Redecentralization of the Web',
  'observation_id': 80,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [80],
  'message': 'Redecentralization of the Web',
  'observation_id': 81,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [81],
  'message': 'Redecentralization of the Web',
  'observation_id': 82,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [82],
  'message': 'Redecentralization of the Web',
  'observation_id': 83,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [83],
  'message': 'Redecentralization of the Web',
  'observation_id': 84,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [84],
  'message': 'Redecentralization of the Web',
  'observation_id': 85,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [85],
  'message': 'Redecentralization of the Web',
  'observation_id': 86,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [86],
  'message': 'Redecentralization of the Web',
  'observation_id': 87,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [87],
  'message': 'Redecentralization of the Web',
  'observation_id': 88,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [88],
  'message': 'Redecentralization of the Web',
  'observation_id': 89,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [89],
  'message': 'Redecentralization of the Web',
  'observation_id': 90,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [90],
  'message': 'Redecentralization of the Web',
  'observation_id': 91,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [91],
  'message': 'Redecentralization of the Web',
  'observation_id': 92,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [92],
  'message': 'Redecentralization of the Web',
  'observation_id': 93,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [93],
  'message': 'Redecentralization of the Web',
  'observation_id': 94,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [94],
  'message': 'Redecentralization of the Web',
  'observation_id': 95,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [95],
  'message': 'Redecentralization of the Web',
  'observation_id': 96,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [96],
  'message': 'Redecentralization of the Web',
  'observation_id': 97,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [97],
  'message': 'Redecentralization of the Web',
  'observation_id': 98,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [98],
  'message': 'Redecentralization of the Web',
  'observation_id': 99,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'}]

HISTORY = {'A': {'B': 1.0, 'C': 1.0, 'D': 1.0},
 'B': {'A': 0, 'C': 0, 'D': 1.0},
 'C': {'A': 1.0, 'B': 1.0, 'D': 1.0},
 'D': {'A': 1.0, 'B': 1.0, 'C': 1.0}}

SCALES_PER_AGENT = {'A': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'B': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'C': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'D': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'}}

METRICS_PER_AGENT = {'A': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'B': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'C': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'D': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}}}

DESCRIPTION = 'Scalability Test with observation upscaling for WI 2020'

