
NAME = 'Scale Obs 500'

AGENTS = ['A', 'B', 'C', 'D']

OBSERVATIONS = [{'author': 'A',
  'before': [],
  'message': 'Redecentralization of the Web',
  'observation_id': 0,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [0],
  'message': 'Redecentralization of the Web',
  'observation_id': 1,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [1],
  'message': 'Redecentralization of the Web',
  'observation_id': 2,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [2],
  'message': 'Redecentralization of the Web',
  'observation_id': 3,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [3],
  'message': 'Redecentralization of the Web',
  'observation_id': 4,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [4],
  'message': 'Redecentralization of the Web',
  'observation_id': 5,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [5],
  'message': 'Redecentralization of the Web',
  'observation_id': 6,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [6],
  'message': 'Redecentralization of the Web',
  'observation_id': 7,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [7],
  'message': 'Redecentralization of the Web',
  'observation_id': 8,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [8],
  'message': 'Redecentralization of the Web',
  'observation_id': 9,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [9],
  'message': 'Redecentralization of the Web',
  'observation_id': 10,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [10],
  'message': 'Redecentralization of the Web',
  'observation_id': 11,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [11],
  'message': 'Redecentralization of the Web',
  'observation_id': 12,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [12],
  'message': 'Redecentralization of the Web',
  'observation_id': 13,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [13],
  'message': 'Redecentralization of the Web',
  'observation_id': 14,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [14],
  'message': 'Redecentralization of the Web',
  'observation_id': 15,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [15],
  'message': 'Redecentralization of the Web',
  'observation_id': 16,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [16],
  'message': 'Redecentralization of the Web',
  'observation_id': 17,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [17],
  'message': 'Redecentralization of the Web',
  'observation_id': 18,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [18],
  'message': 'Redecentralization of the Web',
  'observation_id': 19,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [19],
  'message': 'Redecentralization of the Web',
  'observation_id': 20,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [20],
  'message': 'Redecentralization of the Web',
  'observation_id': 21,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [21],
  'message': 'Redecentralization of the Web',
  'observation_id': 22,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [22],
  'message': 'Redecentralization of the Web',
  'observation_id': 23,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [23],
  'message': 'Redecentralization of the Web',
  'observation_id': 24,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [24],
  'message': 'Redecentralization of the Web',
  'observation_id': 25,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [25],
  'message': 'Redecentralization of the Web',
  'observation_id': 26,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [26],
  'message': 'Redecentralization of the Web',
  'observation_id': 27,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [27],
  'message': 'Redecentralization of the Web',
  'observation_id': 28,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [28],
  'message': 'Redecentralization of the Web',
  'observation_id': 29,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [29],
  'message': 'Redecentralization of the Web',
  'observation_id': 30,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [30],
  'message': 'Redecentralization of the Web',
  'observation_id': 31,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [31],
  'message': 'Redecentralization of the Web',
  'observation_id': 32,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [32],
  'message': 'Redecentralization of the Web',
  'observation_id': 33,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [33],
  'message': 'Redecentralization of the Web',
  'observation_id': 34,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [34],
  'message': 'Redecentralization of the Web',
  'observation_id': 35,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [35],
  'message': 'Redecentralization of the Web',
  'observation_id': 36,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [36],
  'message': 'Redecentralization of the Web',
  'observation_id': 37,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [37],
  'message': 'Redecentralization of the Web',
  'observation_id': 38,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [38],
  'message': 'Redecentralization of the Web',
  'observation_id': 39,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [39],
  'message': 'Redecentralization of the Web',
  'observation_id': 40,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [40],
  'message': 'Redecentralization of the Web',
  'observation_id': 41,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [41],
  'message': 'Redecentralization of the Web',
  'observation_id': 42,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [42],
  'message': 'Redecentralization of the Web',
  'observation_id': 43,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [43],
  'message': 'Redecentralization of the Web',
  'observation_id': 44,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [44],
  'message': 'Redecentralization of the Web',
  'observation_id': 45,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [45],
  'message': 'Redecentralization of the Web',
  'observation_id': 46,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [46],
  'message': 'Redecentralization of the Web',
  'observation_id': 47,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [47],
  'message': 'Redecentralization of the Web',
  'observation_id': 48,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [48],
  'message': 'Redecentralization of the Web',
  'observation_id': 49,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [49],
  'message': 'Redecentralization of the Web',
  'observation_id': 50,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [50],
  'message': 'Redecentralization of the Web',
  'observation_id': 51,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [51],
  'message': 'Redecentralization of the Web',
  'observation_id': 52,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [52],
  'message': 'Redecentralization of the Web',
  'observation_id': 53,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [53],
  'message': 'Redecentralization of the Web',
  'observation_id': 54,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [54],
  'message': 'Redecentralization of the Web',
  'observation_id': 55,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [55],
  'message': 'Redecentralization of the Web',
  'observation_id': 56,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [56],
  'message': 'Redecentralization of the Web',
  'observation_id': 57,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [57],
  'message': 'Redecentralization of the Web',
  'observation_id': 58,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [58],
  'message': 'Redecentralization of the Web',
  'observation_id': 59,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [59],
  'message': 'Redecentralization of the Web',
  'observation_id': 60,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [60],
  'message': 'Redecentralization of the Web',
  'observation_id': 61,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [61],
  'message': 'Redecentralization of the Web',
  'observation_id': 62,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [62],
  'message': 'Redecentralization of the Web',
  'observation_id': 63,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [63],
  'message': 'Redecentralization of the Web',
  'observation_id': 64,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [64],
  'message': 'Redecentralization of the Web',
  'observation_id': 65,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [65],
  'message': 'Redecentralization of the Web',
  'observation_id': 66,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [66],
  'message': 'Redecentralization of the Web',
  'observation_id': 67,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [67],
  'message': 'Redecentralization of the Web',
  'observation_id': 68,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [68],
  'message': 'Redecentralization of the Web',
  'observation_id': 69,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [69],
  'message': 'Redecentralization of the Web',
  'observation_id': 70,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [70],
  'message': 'Redecentralization of the Web',
  'observation_id': 71,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [71],
  'message': 'Redecentralization of the Web',
  'observation_id': 72,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [72],
  'message': 'Redecentralization of the Web',
  'observation_id': 73,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [73],
  'message': 'Redecentralization of the Web',
  'observation_id': 74,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [74],
  'message': 'Redecentralization of the Web',
  'observation_id': 75,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [75],
  'message': 'Redecentralization of the Web',
  'observation_id': 76,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [76],
  'message': 'Redecentralization of the Web',
  'observation_id': 77,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [77],
  'message': 'Redecentralization of the Web',
  'observation_id': 78,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [78],
  'message': 'Redecentralization of the Web',
  'observation_id': 79,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [79],
  'message': 'Redecentralization of the Web',
  'observation_id': 80,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [80],
  'message': 'Redecentralization of the Web',
  'observation_id': 81,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [81],
  'message': 'Redecentralization of the Web',
  'observation_id': 82,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [82],
  'message': 'Redecentralization of the Web',
  'observation_id': 83,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [83],
  'message': 'Redecentralization of the Web',
  'observation_id': 84,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [84],
  'message': 'Redecentralization of the Web',
  'observation_id': 85,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [85],
  'message': 'Redecentralization of the Web',
  'observation_id': 86,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [86],
  'message': 'Redecentralization of the Web',
  'observation_id': 87,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [87],
  'message': 'Redecentralization of the Web',
  'observation_id': 88,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [88],
  'message': 'Redecentralization of the Web',
  'observation_id': 89,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [89],
  'message': 'Redecentralization of the Web',
  'observation_id': 90,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [90],
  'message': 'Redecentralization of the Web',
  'observation_id': 91,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [91],
  'message': 'Redecentralization of the Web',
  'observation_id': 92,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [92],
  'message': 'Redecentralization of the Web',
  'observation_id': 93,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [93],
  'message': 'Redecentralization of the Web',
  'observation_id': 94,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [94],
  'message': 'Redecentralization of the Web',
  'observation_id': 95,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [95],
  'message': 'Redecentralization of the Web',
  'observation_id': 96,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [96],
  'message': 'Redecentralization of the Web',
  'observation_id': 97,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [97],
  'message': 'Redecentralization of the Web',
  'observation_id': 98,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [98],
  'message': 'Redecentralization of the Web',
  'observation_id': 99,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [99],
  'message': 'Redecentralization of the Web',
  'observation_id': 100,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [100],
  'message': 'Redecentralization of the Web',
  'observation_id': 101,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [101],
  'message': 'Redecentralization of the Web',
  'observation_id': 102,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [102],
  'message': 'Redecentralization of the Web',
  'observation_id': 103,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [103],
  'message': 'Redecentralization of the Web',
  'observation_id': 104,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [104],
  'message': 'Redecentralization of the Web',
  'observation_id': 105,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [105],
  'message': 'Redecentralization of the Web',
  'observation_id': 106,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [106],
  'message': 'Redecentralization of the Web',
  'observation_id': 107,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [107],
  'message': 'Redecentralization of the Web',
  'observation_id': 108,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [108],
  'message': 'Redecentralization of the Web',
  'observation_id': 109,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [109],
  'message': 'Redecentralization of the Web',
  'observation_id': 110,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [110],
  'message': 'Redecentralization of the Web',
  'observation_id': 111,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [111],
  'message': 'Redecentralization of the Web',
  'observation_id': 112,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [112],
  'message': 'Redecentralization of the Web',
  'observation_id': 113,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [113],
  'message': 'Redecentralization of the Web',
  'observation_id': 114,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [114],
  'message': 'Redecentralization of the Web',
  'observation_id': 115,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [115],
  'message': 'Redecentralization of the Web',
  'observation_id': 116,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [116],
  'message': 'Redecentralization of the Web',
  'observation_id': 117,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [117],
  'message': 'Redecentralization of the Web',
  'observation_id': 118,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [118],
  'message': 'Redecentralization of the Web',
  'observation_id': 119,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [119],
  'message': 'Redecentralization of the Web',
  'observation_id': 120,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [120],
  'message': 'Redecentralization of the Web',
  'observation_id': 121,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [121],
  'message': 'Redecentralization of the Web',
  'observation_id': 122,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [122],
  'message': 'Redecentralization of the Web',
  'observation_id': 123,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [123],
  'message': 'Redecentralization of the Web',
  'observation_id': 124,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [124],
  'message': 'Redecentralization of the Web',
  'observation_id': 125,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [125],
  'message': 'Redecentralization of the Web',
  'observation_id': 126,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [126],
  'message': 'Redecentralization of the Web',
  'observation_id': 127,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [127],
  'message': 'Redecentralization of the Web',
  'observation_id': 128,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [128],
  'message': 'Redecentralization of the Web',
  'observation_id': 129,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [129],
  'message': 'Redecentralization of the Web',
  'observation_id': 130,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [130],
  'message': 'Redecentralization of the Web',
  'observation_id': 131,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [131],
  'message': 'Redecentralization of the Web',
  'observation_id': 132,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [132],
  'message': 'Redecentralization of the Web',
  'observation_id': 133,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [133],
  'message': 'Redecentralization of the Web',
  'observation_id': 134,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [134],
  'message': 'Redecentralization of the Web',
  'observation_id': 135,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [135],
  'message': 'Redecentralization of the Web',
  'observation_id': 136,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [136],
  'message': 'Redecentralization of the Web',
  'observation_id': 137,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [137],
  'message': 'Redecentralization of the Web',
  'observation_id': 138,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [138],
  'message': 'Redecentralization of the Web',
  'observation_id': 139,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [139],
  'message': 'Redecentralization of the Web',
  'observation_id': 140,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [140],
  'message': 'Redecentralization of the Web',
  'observation_id': 141,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [141],
  'message': 'Redecentralization of the Web',
  'observation_id': 142,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [142],
  'message': 'Redecentralization of the Web',
  'observation_id': 143,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [143],
  'message': 'Redecentralization of the Web',
  'observation_id': 144,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [144],
  'message': 'Redecentralization of the Web',
  'observation_id': 145,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [145],
  'message': 'Redecentralization of the Web',
  'observation_id': 146,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [146],
  'message': 'Redecentralization of the Web',
  'observation_id': 147,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [147],
  'message': 'Redecentralization of the Web',
  'observation_id': 148,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [148],
  'message': 'Redecentralization of the Web',
  'observation_id': 149,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [149],
  'message': 'Redecentralization of the Web',
  'observation_id': 150,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [150],
  'message': 'Redecentralization of the Web',
  'observation_id': 151,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [151],
  'message': 'Redecentralization of the Web',
  'observation_id': 152,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [152],
  'message': 'Redecentralization of the Web',
  'observation_id': 153,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [153],
  'message': 'Redecentralization of the Web',
  'observation_id': 154,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [154],
  'message': 'Redecentralization of the Web',
  'observation_id': 155,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [155],
  'message': 'Redecentralization of the Web',
  'observation_id': 156,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [156],
  'message': 'Redecentralization of the Web',
  'observation_id': 157,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [157],
  'message': 'Redecentralization of the Web',
  'observation_id': 158,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [158],
  'message': 'Redecentralization of the Web',
  'observation_id': 159,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [159],
  'message': 'Redecentralization of the Web',
  'observation_id': 160,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [160],
  'message': 'Redecentralization of the Web',
  'observation_id': 161,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [161],
  'message': 'Redecentralization of the Web',
  'observation_id': 162,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [162],
  'message': 'Redecentralization of the Web',
  'observation_id': 163,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [163],
  'message': 'Redecentralization of the Web',
  'observation_id': 164,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [164],
  'message': 'Redecentralization of the Web',
  'observation_id': 165,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [165],
  'message': 'Redecentralization of the Web',
  'observation_id': 166,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [166],
  'message': 'Redecentralization of the Web',
  'observation_id': 167,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [167],
  'message': 'Redecentralization of the Web',
  'observation_id': 168,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [168],
  'message': 'Redecentralization of the Web',
  'observation_id': 169,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [169],
  'message': 'Redecentralization of the Web',
  'observation_id': 170,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [170],
  'message': 'Redecentralization of the Web',
  'observation_id': 171,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [171],
  'message': 'Redecentralization of the Web',
  'observation_id': 172,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [172],
  'message': 'Redecentralization of the Web',
  'observation_id': 173,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [173],
  'message': 'Redecentralization of the Web',
  'observation_id': 174,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [174],
  'message': 'Redecentralization of the Web',
  'observation_id': 175,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [175],
  'message': 'Redecentralization of the Web',
  'observation_id': 176,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [176],
  'message': 'Redecentralization of the Web',
  'observation_id': 177,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [177],
  'message': 'Redecentralization of the Web',
  'observation_id': 178,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [178],
  'message': 'Redecentralization of the Web',
  'observation_id': 179,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [179],
  'message': 'Redecentralization of the Web',
  'observation_id': 180,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [180],
  'message': 'Redecentralization of the Web',
  'observation_id': 181,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [181],
  'message': 'Redecentralization of the Web',
  'observation_id': 182,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [182],
  'message': 'Redecentralization of the Web',
  'observation_id': 183,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [183],
  'message': 'Redecentralization of the Web',
  'observation_id': 184,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [184],
  'message': 'Redecentralization of the Web',
  'observation_id': 185,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [185],
  'message': 'Redecentralization of the Web',
  'observation_id': 186,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [186],
  'message': 'Redecentralization of the Web',
  'observation_id': 187,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [187],
  'message': 'Redecentralization of the Web',
  'observation_id': 188,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [188],
  'message': 'Redecentralization of the Web',
  'observation_id': 189,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [189],
  'message': 'Redecentralization of the Web',
  'observation_id': 190,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [190],
  'message': 'Redecentralization of the Web',
  'observation_id': 191,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [191],
  'message': 'Redecentralization of the Web',
  'observation_id': 192,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [192],
  'message': 'Redecentralization of the Web',
  'observation_id': 193,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [193],
  'message': 'Redecentralization of the Web',
  'observation_id': 194,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [194],
  'message': 'Redecentralization of the Web',
  'observation_id': 195,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [195],
  'message': 'Redecentralization of the Web',
  'observation_id': 196,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [196],
  'message': 'Redecentralization of the Web',
  'observation_id': 197,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [197],
  'message': 'Redecentralization of the Web',
  'observation_id': 198,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [198],
  'message': 'Redecentralization of the Web',
  'observation_id': 199,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [199],
  'message': 'Redecentralization of the Web',
  'observation_id': 200,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [200],
  'message': 'Redecentralization of the Web',
  'observation_id': 201,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [201],
  'message': 'Redecentralization of the Web',
  'observation_id': 202,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [202],
  'message': 'Redecentralization of the Web',
  'observation_id': 203,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [203],
  'message': 'Redecentralization of the Web',
  'observation_id': 204,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [204],
  'message': 'Redecentralization of the Web',
  'observation_id': 205,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [205],
  'message': 'Redecentralization of the Web',
  'observation_id': 206,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [206],
  'message': 'Redecentralization of the Web',
  'observation_id': 207,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [207],
  'message': 'Redecentralization of the Web',
  'observation_id': 208,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [208],
  'message': 'Redecentralization of the Web',
  'observation_id': 209,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [209],
  'message': 'Redecentralization of the Web',
  'observation_id': 210,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [210],
  'message': 'Redecentralization of the Web',
  'observation_id': 211,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [211],
  'message': 'Redecentralization of the Web',
  'observation_id': 212,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [212],
  'message': 'Redecentralization of the Web',
  'observation_id': 213,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [213],
  'message': 'Redecentralization of the Web',
  'observation_id': 214,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [214],
  'message': 'Redecentralization of the Web',
  'observation_id': 215,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [215],
  'message': 'Redecentralization of the Web',
  'observation_id': 216,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [216],
  'message': 'Redecentralization of the Web',
  'observation_id': 217,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [217],
  'message': 'Redecentralization of the Web',
  'observation_id': 218,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [218],
  'message': 'Redecentralization of the Web',
  'observation_id': 219,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [219],
  'message': 'Redecentralization of the Web',
  'observation_id': 220,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [220],
  'message': 'Redecentralization of the Web',
  'observation_id': 221,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [221],
  'message': 'Redecentralization of the Web',
  'observation_id': 222,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [222],
  'message': 'Redecentralization of the Web',
  'observation_id': 223,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [223],
  'message': 'Redecentralization of the Web',
  'observation_id': 224,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [224],
  'message': 'Redecentralization of the Web',
  'observation_id': 225,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [225],
  'message': 'Redecentralization of the Web',
  'observation_id': 226,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [226],
  'message': 'Redecentralization of the Web',
  'observation_id': 227,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [227],
  'message': 'Redecentralization of the Web',
  'observation_id': 228,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [228],
  'message': 'Redecentralization of the Web',
  'observation_id': 229,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [229],
  'message': 'Redecentralization of the Web',
  'observation_id': 230,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [230],
  'message': 'Redecentralization of the Web',
  'observation_id': 231,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [231],
  'message': 'Redecentralization of the Web',
  'observation_id': 232,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [232],
  'message': 'Redecentralization of the Web',
  'observation_id': 233,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [233],
  'message': 'Redecentralization of the Web',
  'observation_id': 234,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [234],
  'message': 'Redecentralization of the Web',
  'observation_id': 235,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [235],
  'message': 'Redecentralization of the Web',
  'observation_id': 236,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [236],
  'message': 'Redecentralization of the Web',
  'observation_id': 237,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [237],
  'message': 'Redecentralization of the Web',
  'observation_id': 238,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [238],
  'message': 'Redecentralization of the Web',
  'observation_id': 239,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [239],
  'message': 'Redecentralization of the Web',
  'observation_id': 240,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [240],
  'message': 'Redecentralization of the Web',
  'observation_id': 241,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [241],
  'message': 'Redecentralization of the Web',
  'observation_id': 242,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [242],
  'message': 'Redecentralization of the Web',
  'observation_id': 243,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [243],
  'message': 'Redecentralization of the Web',
  'observation_id': 244,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [244],
  'message': 'Redecentralization of the Web',
  'observation_id': 245,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [245],
  'message': 'Redecentralization of the Web',
  'observation_id': 246,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [246],
  'message': 'Redecentralization of the Web',
  'observation_id': 247,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [247],
  'message': 'Redecentralization of the Web',
  'observation_id': 248,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [248],
  'message': 'Redecentralization of the Web',
  'observation_id': 249,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [249],
  'message': 'Redecentralization of the Web',
  'observation_id': 250,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [250],
  'message': 'Redecentralization of the Web',
  'observation_id': 251,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [251],
  'message': 'Redecentralization of the Web',
  'observation_id': 252,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [252],
  'message': 'Redecentralization of the Web',
  'observation_id': 253,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [253],
  'message': 'Redecentralization of the Web',
  'observation_id': 254,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [254],
  'message': 'Redecentralization of the Web',
  'observation_id': 255,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [255],
  'message': 'Redecentralization of the Web',
  'observation_id': 256,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [256],
  'message': 'Redecentralization of the Web',
  'observation_id': 257,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [257],
  'message': 'Redecentralization of the Web',
  'observation_id': 258,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [258],
  'message': 'Redecentralization of the Web',
  'observation_id': 259,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [259],
  'message': 'Redecentralization of the Web',
  'observation_id': 260,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [260],
  'message': 'Redecentralization of the Web',
  'observation_id': 261,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [261],
  'message': 'Redecentralization of the Web',
  'observation_id': 262,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [262],
  'message': 'Redecentralization of the Web',
  'observation_id': 263,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [263],
  'message': 'Redecentralization of the Web',
  'observation_id': 264,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [264],
  'message': 'Redecentralization of the Web',
  'observation_id': 265,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [265],
  'message': 'Redecentralization of the Web',
  'observation_id': 266,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [266],
  'message': 'Redecentralization of the Web',
  'observation_id': 267,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [267],
  'message': 'Redecentralization of the Web',
  'observation_id': 268,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [268],
  'message': 'Redecentralization of the Web',
  'observation_id': 269,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [269],
  'message': 'Redecentralization of the Web',
  'observation_id': 270,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [270],
  'message': 'Redecentralization of the Web',
  'observation_id': 271,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [271],
  'message': 'Redecentralization of the Web',
  'observation_id': 272,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [272],
  'message': 'Redecentralization of the Web',
  'observation_id': 273,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [273],
  'message': 'Redecentralization of the Web',
  'observation_id': 274,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [274],
  'message': 'Redecentralization of the Web',
  'observation_id': 275,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [275],
  'message': 'Redecentralization of the Web',
  'observation_id': 276,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [276],
  'message': 'Redecentralization of the Web',
  'observation_id': 277,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [277],
  'message': 'Redecentralization of the Web',
  'observation_id': 278,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [278],
  'message': 'Redecentralization of the Web',
  'observation_id': 279,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [279],
  'message': 'Redecentralization of the Web',
  'observation_id': 280,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [280],
  'message': 'Redecentralization of the Web',
  'observation_id': 281,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [281],
  'message': 'Redecentralization of the Web',
  'observation_id': 282,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [282],
  'message': 'Redecentralization of the Web',
  'observation_id': 283,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [283],
  'message': 'Redecentralization of the Web',
  'observation_id': 284,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [284],
  'message': 'Redecentralization of the Web',
  'observation_id': 285,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [285],
  'message': 'Redecentralization of the Web',
  'observation_id': 286,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [286],
  'message': 'Redecentralization of the Web',
  'observation_id': 287,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [287],
  'message': 'Redecentralization of the Web',
  'observation_id': 288,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [288],
  'message': 'Redecentralization of the Web',
  'observation_id': 289,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [289],
  'message': 'Redecentralization of the Web',
  'observation_id': 290,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [290],
  'message': 'Redecentralization of the Web',
  'observation_id': 291,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [291],
  'message': 'Redecentralization of the Web',
  'observation_id': 292,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [292],
  'message': 'Redecentralization of the Web',
  'observation_id': 293,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [293],
  'message': 'Redecentralization of the Web',
  'observation_id': 294,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [294],
  'message': 'Redecentralization of the Web',
  'observation_id': 295,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [295],
  'message': 'Redecentralization of the Web',
  'observation_id': 296,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [296],
  'message': 'Redecentralization of the Web',
  'observation_id': 297,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [297],
  'message': 'Redecentralization of the Web',
  'observation_id': 298,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [298],
  'message': 'Redecentralization of the Web',
  'observation_id': 299,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [299],
  'message': 'Redecentralization of the Web',
  'observation_id': 300,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [300],
  'message': 'Redecentralization of the Web',
  'observation_id': 301,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [301],
  'message': 'Redecentralization of the Web',
  'observation_id': 302,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [302],
  'message': 'Redecentralization of the Web',
  'observation_id': 303,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [303],
  'message': 'Redecentralization of the Web',
  'observation_id': 304,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [304],
  'message': 'Redecentralization of the Web',
  'observation_id': 305,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [305],
  'message': 'Redecentralization of the Web',
  'observation_id': 306,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [306],
  'message': 'Redecentralization of the Web',
  'observation_id': 307,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [307],
  'message': 'Redecentralization of the Web',
  'observation_id': 308,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [308],
  'message': 'Redecentralization of the Web',
  'observation_id': 309,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [309],
  'message': 'Redecentralization of the Web',
  'observation_id': 310,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [310],
  'message': 'Redecentralization of the Web',
  'observation_id': 311,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [311],
  'message': 'Redecentralization of the Web',
  'observation_id': 312,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [312],
  'message': 'Redecentralization of the Web',
  'observation_id': 313,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [313],
  'message': 'Redecentralization of the Web',
  'observation_id': 314,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [314],
  'message': 'Redecentralization of the Web',
  'observation_id': 315,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [315],
  'message': 'Redecentralization of the Web',
  'observation_id': 316,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [316],
  'message': 'Redecentralization of the Web',
  'observation_id': 317,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [317],
  'message': 'Redecentralization of the Web',
  'observation_id': 318,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [318],
  'message': 'Redecentralization of the Web',
  'observation_id': 319,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [319],
  'message': 'Redecentralization of the Web',
  'observation_id': 320,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [320],
  'message': 'Redecentralization of the Web',
  'observation_id': 321,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [321],
  'message': 'Redecentralization of the Web',
  'observation_id': 322,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [322],
  'message': 'Redecentralization of the Web',
  'observation_id': 323,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [323],
  'message': 'Redecentralization of the Web',
  'observation_id': 324,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [324],
  'message': 'Redecentralization of the Web',
  'observation_id': 325,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [325],
  'message': 'Redecentralization of the Web',
  'observation_id': 326,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [326],
  'message': 'Redecentralization of the Web',
  'observation_id': 327,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [327],
  'message': 'Redecentralization of the Web',
  'observation_id': 328,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [328],
  'message': 'Redecentralization of the Web',
  'observation_id': 329,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [329],
  'message': 'Redecentralization of the Web',
  'observation_id': 330,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [330],
  'message': 'Redecentralization of the Web',
  'observation_id': 331,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [331],
  'message': 'Redecentralization of the Web',
  'observation_id': 332,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [332],
  'message': 'Redecentralization of the Web',
  'observation_id': 333,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [333],
  'message': 'Redecentralization of the Web',
  'observation_id': 334,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [334],
  'message': 'Redecentralization of the Web',
  'observation_id': 335,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [335],
  'message': 'Redecentralization of the Web',
  'observation_id': 336,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [336],
  'message': 'Redecentralization of the Web',
  'observation_id': 337,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [337],
  'message': 'Redecentralization of the Web',
  'observation_id': 338,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [338],
  'message': 'Redecentralization of the Web',
  'observation_id': 339,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [339],
  'message': 'Redecentralization of the Web',
  'observation_id': 340,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [340],
  'message': 'Redecentralization of the Web',
  'observation_id': 341,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [341],
  'message': 'Redecentralization of the Web',
  'observation_id': 342,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [342],
  'message': 'Redecentralization of the Web',
  'observation_id': 343,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [343],
  'message': 'Redecentralization of the Web',
  'observation_id': 344,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [344],
  'message': 'Redecentralization of the Web',
  'observation_id': 345,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [345],
  'message': 'Redecentralization of the Web',
  'observation_id': 346,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [346],
  'message': 'Redecentralization of the Web',
  'observation_id': 347,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [347],
  'message': 'Redecentralization of the Web',
  'observation_id': 348,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [348],
  'message': 'Redecentralization of the Web',
  'observation_id': 349,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [349],
  'message': 'Redecentralization of the Web',
  'observation_id': 350,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [350],
  'message': 'Redecentralization of the Web',
  'observation_id': 351,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [351],
  'message': 'Redecentralization of the Web',
  'observation_id': 352,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [352],
  'message': 'Redecentralization of the Web',
  'observation_id': 353,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [353],
  'message': 'Redecentralization of the Web',
  'observation_id': 354,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [354],
  'message': 'Redecentralization of the Web',
  'observation_id': 355,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [355],
  'message': 'Redecentralization of the Web',
  'observation_id': 356,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [356],
  'message': 'Redecentralization of the Web',
  'observation_id': 357,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [357],
  'message': 'Redecentralization of the Web',
  'observation_id': 358,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [358],
  'message': 'Redecentralization of the Web',
  'observation_id': 359,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [359],
  'message': 'Redecentralization of the Web',
  'observation_id': 360,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [360],
  'message': 'Redecentralization of the Web',
  'observation_id': 361,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [361],
  'message': 'Redecentralization of the Web',
  'observation_id': 362,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [362],
  'message': 'Redecentralization of the Web',
  'observation_id': 363,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [363],
  'message': 'Redecentralization of the Web',
  'observation_id': 364,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [364],
  'message': 'Redecentralization of the Web',
  'observation_id': 365,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [365],
  'message': 'Redecentralization of the Web',
  'observation_id': 366,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [366],
  'message': 'Redecentralization of the Web',
  'observation_id': 367,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [367],
  'message': 'Redecentralization of the Web',
  'observation_id': 368,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [368],
  'message': 'Redecentralization of the Web',
  'observation_id': 369,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [369],
  'message': 'Redecentralization of the Web',
  'observation_id': 370,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [370],
  'message': 'Redecentralization of the Web',
  'observation_id': 371,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [371],
  'message': 'Redecentralization of the Web',
  'observation_id': 372,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [372],
  'message': 'Redecentralization of the Web',
  'observation_id': 373,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [373],
  'message': 'Redecentralization of the Web',
  'observation_id': 374,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [374],
  'message': 'Redecentralization of the Web',
  'observation_id': 375,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [375],
  'message': 'Redecentralization of the Web',
  'observation_id': 376,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [376],
  'message': 'Redecentralization of the Web',
  'observation_id': 377,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [377],
  'message': 'Redecentralization of the Web',
  'observation_id': 378,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [378],
  'message': 'Redecentralization of the Web',
  'observation_id': 379,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [379],
  'message': 'Redecentralization of the Web',
  'observation_id': 380,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [380],
  'message': 'Redecentralization of the Web',
  'observation_id': 381,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [381],
  'message': 'Redecentralization of the Web',
  'observation_id': 382,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [382],
  'message': 'Redecentralization of the Web',
  'observation_id': 383,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [383],
  'message': 'Redecentralization of the Web',
  'observation_id': 384,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [384],
  'message': 'Redecentralization of the Web',
  'observation_id': 385,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [385],
  'message': 'Redecentralization of the Web',
  'observation_id': 386,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [386],
  'message': 'Redecentralization of the Web',
  'observation_id': 387,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [387],
  'message': 'Redecentralization of the Web',
  'observation_id': 388,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [388],
  'message': 'Redecentralization of the Web',
  'observation_id': 389,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [389],
  'message': 'Redecentralization of the Web',
  'observation_id': 390,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [390],
  'message': 'Redecentralization of the Web',
  'observation_id': 391,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [391],
  'message': 'Redecentralization of the Web',
  'observation_id': 392,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [392],
  'message': 'Redecentralization of the Web',
  'observation_id': 393,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [393],
  'message': 'Redecentralization of the Web',
  'observation_id': 394,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [394],
  'message': 'Redecentralization of the Web',
  'observation_id': 395,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [395],
  'message': 'Redecentralization of the Web',
  'observation_id': 396,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [396],
  'message': 'Redecentralization of the Web',
  'observation_id': 397,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [397],
  'message': 'Redecentralization of the Web',
  'observation_id': 398,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [398],
  'message': 'Redecentralization of the Web',
  'observation_id': 399,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [399],
  'message': 'Redecentralization of the Web',
  'observation_id': 400,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [400],
  'message': 'Redecentralization of the Web',
  'observation_id': 401,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [401],
  'message': 'Redecentralization of the Web',
  'observation_id': 402,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [402],
  'message': 'Redecentralization of the Web',
  'observation_id': 403,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [403],
  'message': 'Redecentralization of the Web',
  'observation_id': 404,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [404],
  'message': 'Redecentralization of the Web',
  'observation_id': 405,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [405],
  'message': 'Redecentralization of the Web',
  'observation_id': 406,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [406],
  'message': 'Redecentralization of the Web',
  'observation_id': 407,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [407],
  'message': 'Redecentralization of the Web',
  'observation_id': 408,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [408],
  'message': 'Redecentralization of the Web',
  'observation_id': 409,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [409],
  'message': 'Redecentralization of the Web',
  'observation_id': 410,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [410],
  'message': 'Redecentralization of the Web',
  'observation_id': 411,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [411],
  'message': 'Redecentralization of the Web',
  'observation_id': 412,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [412],
  'message': 'Redecentralization of the Web',
  'observation_id': 413,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [413],
  'message': 'Redecentralization of the Web',
  'observation_id': 414,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [414],
  'message': 'Redecentralization of the Web',
  'observation_id': 415,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [415],
  'message': 'Redecentralization of the Web',
  'observation_id': 416,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [416],
  'message': 'Redecentralization of the Web',
  'observation_id': 417,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [417],
  'message': 'Redecentralization of the Web',
  'observation_id': 418,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [418],
  'message': 'Redecentralization of the Web',
  'observation_id': 419,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [419],
  'message': 'Redecentralization of the Web',
  'observation_id': 420,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [420],
  'message': 'Redecentralization of the Web',
  'observation_id': 421,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [421],
  'message': 'Redecentralization of the Web',
  'observation_id': 422,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [422],
  'message': 'Redecentralization of the Web',
  'observation_id': 423,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [423],
  'message': 'Redecentralization of the Web',
  'observation_id': 424,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [424],
  'message': 'Redecentralization of the Web',
  'observation_id': 425,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [425],
  'message': 'Redecentralization of the Web',
  'observation_id': 426,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [426],
  'message': 'Redecentralization of the Web',
  'observation_id': 427,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [427],
  'message': 'Redecentralization of the Web',
  'observation_id': 428,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [428],
  'message': 'Redecentralization of the Web',
  'observation_id': 429,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [429],
  'message': 'Redecentralization of the Web',
  'observation_id': 430,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [430],
  'message': 'Redecentralization of the Web',
  'observation_id': 431,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [431],
  'message': 'Redecentralization of the Web',
  'observation_id': 432,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [432],
  'message': 'Redecentralization of the Web',
  'observation_id': 433,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [433],
  'message': 'Redecentralization of the Web',
  'observation_id': 434,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [434],
  'message': 'Redecentralization of the Web',
  'observation_id': 435,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [435],
  'message': 'Redecentralization of the Web',
  'observation_id': 436,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [436],
  'message': 'Redecentralization of the Web',
  'observation_id': 437,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [437],
  'message': 'Redecentralization of the Web',
  'observation_id': 438,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [438],
  'message': 'Redecentralization of the Web',
  'observation_id': 439,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [439],
  'message': 'Redecentralization of the Web',
  'observation_id': 440,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [440],
  'message': 'Redecentralization of the Web',
  'observation_id': 441,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [441],
  'message': 'Redecentralization of the Web',
  'observation_id': 442,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [442],
  'message': 'Redecentralization of the Web',
  'observation_id': 443,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [443],
  'message': 'Redecentralization of the Web',
  'observation_id': 444,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [444],
  'message': 'Redecentralization of the Web',
  'observation_id': 445,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [445],
  'message': 'Redecentralization of the Web',
  'observation_id': 446,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [446],
  'message': 'Redecentralization of the Web',
  'observation_id': 447,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [447],
  'message': 'Redecentralization of the Web',
  'observation_id': 448,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [448],
  'message': 'Redecentralization of the Web',
  'observation_id': 449,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [449],
  'message': 'Redecentralization of the Web',
  'observation_id': 450,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [450],
  'message': 'Redecentralization of the Web',
  'observation_id': 451,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [451],
  'message': 'Redecentralization of the Web',
  'observation_id': 452,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [452],
  'message': 'Redecentralization of the Web',
  'observation_id': 453,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [453],
  'message': 'Redecentralization of the Web',
  'observation_id': 454,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [454],
  'message': 'Redecentralization of the Web',
  'observation_id': 455,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [455],
  'message': 'Redecentralization of the Web',
  'observation_id': 456,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [456],
  'message': 'Redecentralization of the Web',
  'observation_id': 457,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [457],
  'message': 'Redecentralization of the Web',
  'observation_id': 458,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [458],
  'message': 'Redecentralization of the Web',
  'observation_id': 459,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [459],
  'message': 'Redecentralization of the Web',
  'observation_id': 460,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [460],
  'message': 'Redecentralization of the Web',
  'observation_id': 461,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [461],
  'message': 'Redecentralization of the Web',
  'observation_id': 462,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [462],
  'message': 'Redecentralization of the Web',
  'observation_id': 463,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [463],
  'message': 'Redecentralization of the Web',
  'observation_id': 464,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [464],
  'message': 'Redecentralization of the Web',
  'observation_id': 465,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [465],
  'message': 'Redecentralization of the Web',
  'observation_id': 466,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [466],
  'message': 'Redecentralization of the Web',
  'observation_id': 467,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [467],
  'message': 'Redecentralization of the Web',
  'observation_id': 468,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [468],
  'message': 'Redecentralization of the Web',
  'observation_id': 469,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [469],
  'message': 'Redecentralization of the Web',
  'observation_id': 470,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [470],
  'message': 'Redecentralization of the Web',
  'observation_id': 471,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [471],
  'message': 'Redecentralization of the Web',
  'observation_id': 472,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [472],
  'message': 'Redecentralization of the Web',
  'observation_id': 473,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [473],
  'message': 'Redecentralization of the Web',
  'observation_id': 474,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [474],
  'message': 'Redecentralization of the Web',
  'observation_id': 475,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [475],
  'message': 'Redecentralization of the Web',
  'observation_id': 476,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [476],
  'message': 'Redecentralization of the Web',
  'observation_id': 477,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [477],
  'message': 'Redecentralization of the Web',
  'observation_id': 478,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [478],
  'message': 'Redecentralization of the Web',
  'observation_id': 479,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [479],
  'message': 'Redecentralization of the Web',
  'observation_id': 480,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [480],
  'message': 'Redecentralization of the Web',
  'observation_id': 481,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [481],
  'message': 'Redecentralization of the Web',
  'observation_id': 482,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [482],
  'message': 'Redecentralization of the Web',
  'observation_id': 483,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [483],
  'message': 'Redecentralization of the Web',
  'observation_id': 484,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [484],
  'message': 'Redecentralization of the Web',
  'observation_id': 485,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [485],
  'message': 'Redecentralization of the Web',
  'observation_id': 486,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [486],
  'message': 'Redecentralization of the Web',
  'observation_id': 487,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [487],
  'message': 'Redecentralization of the Web',
  'observation_id': 488,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [488],
  'message': 'Redecentralization of the Web',
  'observation_id': 489,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [489],
  'message': 'Redecentralization of the Web',
  'observation_id': 490,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [490],
  'message': 'Redecentralization of the Web',
  'observation_id': 491,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [491],
  'message': 'Redecentralization of the Web',
  'observation_id': 492,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [492],
  'message': 'Redecentralization of the Web',
  'observation_id': 493,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [493],
  'message': 'Redecentralization of the Web',
  'observation_id': 494,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [494],
  'message': 'Redecentralization of the Web',
  'observation_id': 495,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [495],
  'message': 'Redecentralization of the Web',
  'observation_id': 496,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [496],
  'message': 'Redecentralization of the Web',
  'observation_id': 497,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [497],
  'message': 'Redecentralization of the Web',
  'observation_id': 498,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [498],
  'message': 'Redecentralization of the Web',
  'observation_id': 499,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'}]

HISTORY = {'A': {'B': 1.0, 'C': 1.0, 'D': 1.0},
 'B': {'A': 0, 'C': 0, 'D': 1.0},
 'C': {'A': 1.0, 'B': 1.0, 'D': 1.0},
 'D': {'A': 1.0, 'B': 1.0, 'C': 1.0}}

SCALES_PER_AGENT = {'A': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'B': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'C': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'D': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'}}

METRICS_PER_AGENT = {'A': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'B': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'C': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'D': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}}}

DESCRIPTION = 'Scalability Test with observation upscaling for WI 2020'

