
NAME = 'Scale Agents 10'

AGENTS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

OBSERVATIONS = [{'author': 'A',
  'before': [],
  'message': 'Redecentralization of the Web',
  'observation_id': 1,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [1],
  'message': 'Web of Things',
  'observation_id': 2,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'A',
  'before': [2],
  'message': 'Web Assembly',
  'observation_id': 3,
  'receiver': 'B',
  'sender': 'A',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [3],
  'message': 'Semantic Web and Linked Open Data',
  'observation_id': 4,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [4],
  'message': 'Redecentralization of the Web',
  'observation_id': 5,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'},
 {'author': 'C',
  'before': [5],
  'message': 'Web-based learning',
  'observation_id': 6,
  'receiver': 'B',
  'sender': 'C',
  'topic': 'Web Engineering'}]

HISTORY = {'A': {'B': 1.0, 'C': 1.0, 'D': 1.0},
 'B': {'A': 0, 'C': 0, 'D': 1.0},
 'C': {'A': 1.0, 'B': 1.0, 'D': 1.0},
 'D': {'A': 1.0, 'B': 1.0, 'C': 1.0},
 'E': {},
 'F': {},
 'G': {},
 'H': {},
 'I': {},
 'J': {}}

SCALES_PER_AGENT = {'A': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'B': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'C': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'D': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'E': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'F': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'G': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'H': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'I': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'},
 'J': {'cooperation': 0.5,
       'default': 0.0,
       'forgivability': -0.5,
       'maximum': 1.0,
       'minimum': -1.0,
       'name': 'Trust Scale by Marsh and Briggs (2009)',
       'package': 'marsh_briggs_scale'}}

METRICS_PER_AGENT = {'A': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'B': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'C': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'D': {'__final__': {'name': 'weighted_average', 'weights': {}},
       'content_trust.direct_experience': {},
       'content_trust.popularity': {},
       'content_trust.recommendation': {}},
 'E': {'__final__': {'name': 'weighted_average', 'weights': {}}},
 'F': {'__final__': {'name': 'weighted_average', 'weights': {}}},
 'G': {'__final__': {'name': 'weighted_average', 'weights': {}}},
 'H': {'__final__': {'name': 'weighted_average', 'weights': {}}},
 'I': {'__final__': {'name': 'weighted_average', 'weights': {}}},
 'J': {'__final__': {'name': 'weighted_average', 'weights': {}}}}

DESCRIPTION = 'Scalability Test with agent upscaling for WI 2020'

