
NAME = "Scale Agents 200"
DESCRIPTION = "Scalability Test with agent upscaling for WI 2020"

AGENTS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BA', 'BB', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BK', 'BL', 'BM', 'BN', 'BO', 'BP', 'BQ', 'BR', 'BS', 'BT', 'BU', 'BV', 'BW', 'BX', 'BY', 'BZ', 'CA', 'CB', 'CC', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'CK', 'CL', 'CM', 'CN', 'CO', 'CP', 'CQ', 'CR', 'CS', 'CT', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DF', 'DG', 'DH', 'DI', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DO', 'DP', 'DQ', 'DR', 'DS', 'DT', 'DU', 'DV', 'DW', 'DX', 'DY', 'DZ', 'EA', 'EB', 'EC', 'ED', 'EE', 'EF', 'EG', 'EH', 'EI', 'EJ', 'EK', 'EL', 'EM', 'EN', 'EO', 'EP', 'EQ', 'ER', 'ES', 'ET', 'EU', 'EV', 'EW', 'EX', 'EY', 'EZ', 'FA', 'FB', 'FC', 'FD', 'FE', 'FF', 'FG', 'FH', 'FI', 'FJ', 'FK', 'FL', 'FM', 'FN', 'FO', 'FP', 'FQ', 'FR', 'FS', 'FT', 'FU', 'FV', 'FW', 'FX', 'FY', 'FZ', 'GA', 'GB', 'GC', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GJ', 'GK', 'GL', 'GM', 'GN', 'GO', 'GP', 'GQ', 'GR']

AUTHORITIES = {}

OBSERVATIONS = [{'observation_id': 1, 'before': [], 'sender': 'A', 'receiver': 'B', 'author': 'A', 'topic': 'Web Engineering', 'message': 'Redecentralization of the Web'}, {'observation_id': 2, 'before': [1], 'sender': 'A', 'receiver': 'B', 'author': 'A', 'topic': 'Web Engineering', 'message': 'Web of Things'}, {'observation_id': 3, 'before': [2], 'sender': 'A', 'receiver': 'B', 'author': 'A', 'topic': 'Web Engineering', 'message': 'Web Assembly'}, {'observation_id': 4, 'before': [3], 'sender': 'C', 'receiver': 'B', 'author': 'C', 'topic': 'Web Engineering', 'message': 'Semantic Web and Linked Open Data'}, {'observation_id': 5, 'before': [4], 'sender': 'C', 'receiver': 'B', 'author': 'C', 'topic': 'Web Engineering', 'message': 'Redecentralization of the Web'}, {'observation_id': 6, 'before': [5], 'sender': 'C', 'receiver': 'B', 'author': 'C', 'topic': 'Web Engineering', 'message': 'Web-based learning'}]

HISTORY = {'A': {'B': 1.0, 'C': 1.0, 'D': 1.0}, 'B': {'A': 0, 'C': 0, 'D': 1.0}, 'C': {'A': 1.0, 'B': 1.0, 'D': 1.0}, 'D': {'A': 1.0, 'B': 1.0, 'C': 1.0}, 'E': {}, 'F': {}, 'G': {}, 'H': {}, 'I': {}, 'J': {}, 'K': {}, 'L': {}, 'M': {}, 'N': {}, 'O': {}, 'P': {}, 'Q': {}, 'R': {}, 'S': {}, 'T': {}, 'U': {}, 'V': {}, 'W': {}, 'X': {}, 'Y': {}, 'Z': {}, 'AA': {}, 'AB': {}, 'AC': {}, 'AD': {}, 'AE': {}, 'AF': {}, 'AG': {}, 'AH': {}, 'AI': {}, 'AJ': {}, 'AK': {}, 'AL': {}, 'AM': {}, 'AN': {}, 'AO': {}, 'AP': {}, 'AQ': {}, 'AR': {}, 'AS': {}, 'AT': {}, 'AU': {}, 'AV': {}, 'AW': {}, 'AX': {}, 'AY': {}, 'AZ': {}, 'BA': {}, 'BB': {}, 'BC': {}, 'BD': {}, 'BE': {}, 'BF': {}, 'BG': {}, 'BH': {}, 'BI': {}, 'BJ': {}, 'BK': {}, 'BL': {}, 'BM': {}, 'BN': {}, 'BO': {}, 'BP': {}, 'BQ': {}, 'BR': {}, 'BS': {}, 'BT': {}, 'BU': {}, 'BV': {}, 'BW': {}, 'BX': {}, 'BY': {}, 'BZ': {}, 'CA': {}, 'CB': {}, 'CC': {}, 'CD': {}, 'CE': {}, 'CF': {}, 'CG': {}, 'CH': {}, 'CI': {}, 'CJ': {}, 'CK': {}, 'CL': {}, 'CM': {}, 'CN': {}, 'CO': {}, 'CP': {}, 'CQ': {}, 'CR': {}, 'CS': {}, 'CT': {}, 'CU': {}, 'CV': {}, 'CW': {}, 'CX': {}, 'CY': {}, 'CZ': {}, 'DA': {}, 'DB': {}, 'DC': {}, 'DD': {}, 'DE': {}, 'DF': {}, 'DG': {}, 'DH': {}, 'DI': {}, 'DJ': {}, 'DK': {}, 'DL': {}, 'DM': {}, 'DN': {}, 'DO': {}, 'DP': {}, 'DQ': {}, 'DR': {}, 'DS': {}, 'DT': {}, 'DU': {}, 'DV': {}, 'DW': {}, 'DX': {}, 'DY': {}, 'DZ': {}, 'EA': {}, 'EB': {}, 'EC': {}, 'ED': {}, 'EE': {}, 'EF': {}, 'EG': {}, 'EH': {}, 'EI': {}, 'EJ': {}, 'EK': {}, 'EL': {}, 'EM': {}, 'EN': {}, 'EO': {}, 'EP': {}, 'EQ': {}, 'ER': {}, 'ES': {}, 'ET': {}, 'EU': {}, 'EV': {}, 'EW': {}, 'EX': {}, 'EY': {}, 'EZ': {}, 'FA': {}, 'FB': {}, 'FC': {}, 'FD': {}, 'FE': {}, 'FF': {}, 'FG': {}, 'FH': {}, 'FI': {}, 'FJ': {}, 'FK': {}, 'FL': {}, 'FM': {}, 'FN': {}, 'FO': {}, 'FP': {}, 'FQ': {}, 'FR': {}, 'FS': {}, 'FT': {}, 'FU': {}, 'FV': {}, 'FW': {}, 'FX': {}, 'FY': {}, 'FZ': {}, 'GA': {}, 'GB': {}, 'GC': {}, 'GD': {}, 'GE': {}, 'GF': {}, 'GG': {}, 'GH': {}, 'GI': {}, 'GJ': {}, 'GK': {}, 'GL': {}, 'GM': {}, 'GN': {}, 'GO': {}, 'GP': {}, 'GQ': {}, 'GR': {}}

TOPICS = {}

TRUST_THRESHOLDS = {'cooperation': 0.5, 'forgivability': -0.5}

WEIGHTS = {'direct experience': 1.0, 'recommendation': 1.0, 'popularity': 1.0, 'age': 1.0, 'agreement': 1.0, 'authority': 1.0, 'provenance': 1.0, 'recency': 1.0, 'related resource': 1.0, 'specificity': 1.0, 'topic': 1.0}

METRICS_PER_AGENT = {'A': ['direct experience', 'popularity', 'recommendation'], 'B': ['direct experience', 'popularity', 'recommendation'], 'C': ['direct experience', 'popularity', 'recommendation'], 'D': ['direct experience', 'popularity', 'recommendation'], 'E': [], 'F': [], 'G': [], 'H': [], 'I': [], 'J': [], 'K': [], 'L': [], 'M': [], 'N': [], 'O': [], 'P': [], 'Q': [], 'R': [], 'S': [], 'T': [], 'U': [], 'V': [], 'W': [], 'X': [], 'Y': [], 'Z': [], 'AA': [], 'AB': [], 'AC': [], 'AD': [], 'AE': [], 'AF': [], 'AG': [], 'AH': [], 'AI': [], 'AJ': [], 'AK': [], 'AL': [], 'AM': [], 'AN': [], 'AO': [], 'AP': [], 'AQ': [], 'AR': [], 'AS': [], 'AT': [], 'AU': [], 'AV': [], 'AW': [], 'AX': [], 'AY': [], 'AZ': [], 'BA': [], 'BB': [], 'BC': [], 'BD': [], 'BE': [], 'BF': [], 'BG': [], 'BH': [], 'BI': [], 'BJ': [], 'BK': [], 'BL': [], 'BM': [], 'BN': [], 'BO': [], 'BP': [], 'BQ': [], 'BR': [], 'BS': [], 'BT': [], 'BU': [], 'BV': [], 'BW': [], 'BX': [], 'BY': [], 'BZ': [], 'CA': [], 'CB': [], 'CC': [], 'CD': [], 'CE': [], 'CF': [], 'CG': [], 'CH': [], 'CI': [], 'CJ': [], 'CK': [], 'CL': [], 'CM': [], 'CN': [], 'CO': [], 'CP': [], 'CQ': [], 'CR': [], 'CS': [], 'CT': [], 'CU': [], 'CV': [], 'CW': [], 'CX': [], 'CY': [], 'CZ': [], 'DA': [], 'DB': [], 'DC': [], 'DD': [], 'DE': [], 'DF': [], 'DG': [], 'DH': [], 'DI': [], 'DJ': [], 'DK': [], 'DL': [], 'DM': [], 'DN': [], 'DO': [], 'DP': [], 'DQ': [], 'DR': [], 'DS': [], 'DT': [], 'DU': [], 'DV': [], 'DW': [], 'DX': [], 'DY': [], 'DZ': [], 'EA': [], 'EB': [], 'EC': [], 'ED': [], 'EE': [], 'EF': [], 'EG': [], 'EH': [], 'EI': [], 'EJ': [], 'EK': [], 'EL': [], 'EM': [], 'EN': [], 'EO': [], 'EP': [], 'EQ': [], 'ER': [], 'ES': [], 'ET': [], 'EU': [], 'EV': [], 'EW': [], 'EX': [], 'EY': [], 'EZ': [], 'FA': [], 'FB': [], 'FC': [], 'FD': [], 'FE': [], 'FF': [], 'FG': [], 'FH': [], 'FI': [], 'FJ': [], 'FK': [], 'FL': [], 'FM': [], 'FN': [], 'FO': [], 'FP': [], 'FQ': [], 'FR': [], 'FS': [], 'FT': [], 'FU': [], 'FV': [], 'FW': [], 'FX': [], 'FY': [], 'FZ': [], 'GA': [], 'GB': [], 'GC': [], 'GD': [], 'GE': [], 'GF': [], 'GG': [], 'GH': [], 'GI': [], 'GJ': [], 'GK': [], 'GL': [], 'GM': [], 'GN': [], 'GO': [], 'GP': [], 'GQ': [], 'GR': []}

