# Generated by Django 2.1.12 on 2020-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=120)),
                ('max_agents', models.IntegerField(default=0)),
                ('agents_in_use', models.IntegerField(default=0)),
            ],
        ),
    ]
