# Generated by Django 2.1.12 on 2020-05-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustlab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supervisors',
            new_name='Supervisor',
        ),
    ]
