# Generated by Django 2.1.12 on 2021-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustlab', '0002_auto_20200516_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='id',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='channel_name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
