# Generated by Django 2.1.12 on 2022-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustlab', '0003_auto_20210818_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='hostname',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='ip_address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
